#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt>
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
###

name: NEWIFI-D2

on:
  push:
    branches: 
      - master
  schedule:
      - cron: 0 6 * * 5
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Download lede
        run: |
          git clone https://github.com/janethan/lede
          mv ./lede/* ./
      - name: Install addons
        run: |
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
          echo "src-git CloudflareSpeedTest https://github.com/immortalwrt/openwrt-cdnspeedtest" >> ./feeds.conf.default
          cd package
          mkdir openwrt-packages
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          sed -i 's/luci-theme-bootstrap/luci-theme-bootstrap/g' feeds/luci/collections/luci/Makefile
          sed -i 's/192.168.1.1/192.168.100.1/g' package/base-files/files/bin/config_generate
          sed -i 's/OpenWrt/iPhone/g' package/base-files/files/bin/config_generate
          sed -i 's/OpenWrt/CMCC/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          # Device type
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y
          # Gzip
          CONFIG_TARGET_IMAGES_GZIP=y
          # IPv6
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=n
          CONFIG_PACKAGE_ipv6helper=n
          # USB support
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_automount=y
          # CONFIG_PACKAGE_sshtunnel=y
          
          # Filesystem
          CONFIG_PACKAGE_kmod-fs-exfat=y
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-exfat=y
          
          # USPIP service
          CONFIG_PACKAGE_kmod-usb-ohci=y
          # CONFIG_PACKAGE_usbip=y
          # CONFIG_PACKAGE_usbip-client=y
          # CONFIG_PACKAGE_usbip-server=y
          
          # APP
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-advancedsetting=y
          # CONFIG_PACKAGE_luci-app-aliddns=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-meshwizard=y
          # CONFIG_PACKAGE_luci-app-mwan3=y
          # CONFIG_PACKAGE_luci-app-mwan3helper=y
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_fuse-utils=n
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng=n
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui=n
          CONFIG_PACKAGE_luci-app-samba=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_NaiveProxy=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Hysteria=y
          CONFIG_PACKAGE_xray-plugin=y
          # CONFIG_PACKAGE_luci-app-syncdial=y
          # CONFIG_PACKAGE_luci-app-travelmate=y
          # CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-usb-printer=y
          CONFIG_PACKAGE_luci-app-uhttpd=y
          # CONFIG_PACKAGE_luci-app-xlnetacc=y
          # CONFIG_PACKAGE_luci-app-oaf=y
          CONFIG_PACKAGE_luci-app-privoxy=y
          # Open source WIFI driver
          CONFIG_PACKAGE_kmod-mt7603=y
          CONFIG_PACKAGE_kmod-mt7603e=n
          CONFIG_PACKAGE_kmod-mt76x2=y
          # CONFIG_PACKAGE_kmod-mt76x2e=n
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_wpad-openssl=y
          CONFIG_PACKAGE_luci-app-mtwifi=n
          CONFIG_PACKAGE_luci-app-unblockmusic=n
          #CONFIG_PACKAGE_pixiewps=y
          #CONFIG_PACKAGE_reaver=y
          #CONFIG_PACKAGE_aircrack-ng=y
          CONFIG_PACKAGE_kmod-rt2800-usb=y
          CONFIG_PACKAGE_kmod-rt2x00-usb=y
          CONFIG_PACKAGE_kmod-rtl8187=y
          # CONFIG_PACKAGE_kmod-rtl8192ce=y
          # CONFIG_PACKAGE_kmod-rtl8192cu=y
          # CONFIG_PACKAGE_kmod-rtl8192de=y
          # CONFIG_PACKAGE_kmod-rtl8192se=y
          # CONFIG_PACKAGE_kmod-rtl8723bs=y
          # CONFIG_PACKAGE_kmod-rtl8821ae=y
          CONFIG_PACKAGE_kmod-rtl8xxxu=y
          CONFIG_PACKAGE_wireless-tools=y
          
          # Tor
          # CONFIG_PACKAGE_tor=y
          # CONFIG_PACKAGE_tor-gencert=y
          # CONFIG_PACKAGE_tor-geoip=y
          # CONFIG_PACKAGE_tor-resolve=y
          
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt-newifi-d2
          path: bin/targets/ramips/mt7621/*in*
